/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2018-07-05 15:19:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
 
   		String  url =request.getServletPath().substring(1,request.getServletPath().lastIndexOf("/"));  
     	System.out.println("web  URL  路径:"+url);
	
      out.write(" \r\n");
      out.write("\t<!--左边导航开始-->\r\n");
      out.write("\t\t<div class=\"left-nav\">\r\n");
      out.write("\t\t\t<div class=\"panel-group\" id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\">\r\n");
      out.write("\t\t\t    <div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t    <div class=\"panel-heading tab\" role=\"tab\" id=\"headingTwo\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n");
      out.write("\t\t\t\t      \t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t      \t\t<span class=\"fa fa-tags\"></span>\r\n");
      out.write("\t\t\t\t\t        <a class=\"collapsed\" role=\"button\" >\r\n");
      out.write("\t\t\t\t\t         \t 班级管理\r\n");
      out.write("\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t        <span class=\"glyphicon glyphicon-chevron-left icon\" style=\"float: right;font-size: 10px;\"></span>\r\n");
      out.write("\t\t\t\t      \t</h4>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t    <div id=\"collapseTwo\" class=\"panel-collapse collapse ");
if (url.equals("admin")){
      out.write('i');
      out.write('n');
} 
      out.write("\" role=\"tabpanel\" aria-labelledby=\"headingTwo\">\r\n");
      out.write("\t\t\t\t      \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/croom/show\">班级地点列表</a>\r\n");
      out.write("\t\t\t\t      \t</div>\r\n");
      out.write("\t\t\t\t      \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/croom/stop\">班级停用列表</a>\r\n");
      out.write("\t\t\t\t      \t</div>\r\n");
      out.write("\t\t\t\t      \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/croom/start\">班级启用列表</a>\r\n");
      out.write("\t\t\t\t      \t</div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t   <div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t    <div class=\"panel-heading tab\" role=\"tab\" id=\"headingThree\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("\t\t\t\t      \t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t      \t\t<span class=\"fa fa-columns\"></span>\r\n");
      out.write("\t\t\t\t\t        <a class=\"collapsed\" role=\"button\" >\r\n");
      out.write("\t\t\t\t\t         \t 课程管理\r\n");
      out.write("\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t        <span class=\"glyphicon glyphicon-chevron-left icon\" style=\"float: right;font-size: 10px;\"></span>\r\n");
      out.write("\t\t\t\t      \t</h4>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <div id=\"collapseThree\" class=\"panel-collapse collapse ");
if (url.equals("course")){
      out.write('i');
      out.write('n');
} 
      out.write("\" role=\"tabpanel\" aria-labelledby=\"headingThree\">\r\n");
      out.write("\t\t\t\t      \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/course/show\">课程列表</a>\r\n");
      out.write("\t\t\t\t      \t</div>\r\n");
      out.write("\t\t\t\t      \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/course/stop\">课程停用列表</a>\r\n");
      out.write("\t\t\t\t      \t</div>\r\n");
      out.write("\t\t\t\t      \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/course/start\">课程启用列表</a>\r\n");
      out.write("\t\t\t\t      \t</div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  <div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t  \t<div class=\"panel-heading tab\" role=\"tab\" id=\"headingFour\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseFour\" aria-expanded=\"false\" aria-controls=\"collapseFour\">\r\n");
      out.write("\t\t\t  \t\t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t\t  \t\t\t<span class=\"fa fa-user-circle-o\"></span>\r\n");
      out.write("\t\t\t  \t\t\t<a class=\"collapsed\" role=\"button\" >用户管理</a>\r\n");
      out.write("\t\t\t  \t\t\t<span class=\"glyphicon glyphicon-chevron-left icon\" style=\"float: right;font-size: 10px;\"></span>\r\n");
      out.write("\t\t\t  \t\t</h4>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t  \t<div id=\"collapseFour\" class=\"panel-collapse collapse ");
 if(url.equals("user")){
      out.write('i');
      out.write('n');
}
      out.write("\" role=\"tabpanel\" aria-labelledby=\"headingFour\">\r\n");
      out.write("\t\t\t  \t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/student\">学生列表</a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <div class=\"panel-body\">\r\n");
      out.write("\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/teacher\">教师列表</a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <div class=\"panel-body\">\r\n");
      out.write("\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/visitor\">访客列表</a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  <div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t  \t<div class=\"panel-heading tab\" role=\"tab\" id=\"headingFive\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseFive\" aria-expanded=\"false\" aria-controls=\"collapseFive\">\r\n");
      out.write("\t\t\t  \t\t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t\t  \t\t\t<span class=\"fa fa-calendar\"></span>\r\n");
      out.write("\t\t\t  \t\t\t<a class=\"collapsed\" role=\"button\" >教学安排</a>\r\n");
      out.write("\t\t\t  \t\t\t<span class=\"glyphicon glyphicon-chevron-left icon\" style=\"float: right;font-size: 10px;\"></span>\r\n");
      out.write("\t\t\t  \t\t</h4>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t  \t<div id=\"collapseFive\" class=\"panel-collapse collapse ");
 if(url.equals("arrange")){
      out.write('i');
      out.write('n');
}
      out.write("\" role=\"tabpanel\" aria-labelledby=\"headingFive\">\r\n");
      out.write("\t\t\t  \t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/arrange/findAll\">安排教学任务</a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t   <div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t  \t<div class=\"panel-heading tab\" role=\"tab\" id=\"headingSix\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseSix\" aria-expanded=\"false\" aria-controls=\"collapseSix\">\r\n");
      out.write("\t\t\t  \t\t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t\t  \t\t\t<span class=\"fa fa-edit\"></span>\r\n");
      out.write("\t\t\t  \t\t\t<a class=\"collapsed\" role=\"button\" >签到管理</a>\r\n");
      out.write("\t\t\t  \t\t\t<span class=\"glyphicon glyphicon-chevron-left icon\" style=\"float: right;font-size: 10px;\"></span>\r\n");
      out.write("\t\t\t  \t\t</h4>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t  \t<div id=\"collapseSix\" class=\"panel-collapse collapse ");
 if(url.equals("sign")){
      out.write('i');
      out.write('n');
}
      out.write("\" role=\"tabpanel\" aria-labelledby=\"headingSix\">\r\n");
      out.write("\t\t\t  \t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/class/findClassAll\">分配所在班级</a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t  \t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sign/findAll\">查看签到记录</a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t   <div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t  \t<div class=\"panel-heading tab\" role=\"tab\" id=\"headingSeven\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseSeven\" aria-expanded=\"false\" aria-controls=\"collapseSeven\">\r\n");
      out.write("\t\t\t  \t\t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t\t  \t\t\t<span class=\"fa fa-bar-chart\"></span>\r\n");
      out.write("\t\t\t  \t\t\t<a class=\"collapsed\" role=\"button\" >报表管理</a>\r\n");
      out.write("\t\t\t  \t\t\t<span class=\"glyphicon glyphicon-chevron-left icon\" style=\"float: right;font-size: 10px;\"></span>\r\n");
      out.write("\t\t\t  \t\t</h4>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t  \t<div id=\"collapseSeven\" class=\"panel-collapse collapse ");
 if(url.equals("chart")){
      out.write('i');
      out.write('n');
}
      out.write("\" role=\"tabpanel\" aria-labelledby=\"headingSeven\">\r\n");
      out.write("\t\t\t  \t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t      \t\t<span class=\"glyphicon glyphicon-chevron-right\" style=\"padding-left: 25px;font-size: 13px;\"></span>\r\n");
      out.write("\t\t\t        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/student/total?classId=1\">月签到报表</a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//箭头方向0向左\r\n");
      out.write("\t\tvar arr=new Array();\r\n");
      out.write("\t\tfor (var i=0;i<$('.tab').length;i++) {\r\n");
      out.write("\t\t\tarr[i]=0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar flag=0;\r\n");
      out.write("\t\t$('.tab').each(function(i){\r\n");
      out.write("\t\t\t$(this).click(function(){\r\n");
      out.write("\t\t\t\tconsole.log($(this).children().eq(0))\r\n");
      out.write("\t\t\t\tif(arr[i] == 0){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(this).children().eq(0).children().last().removeClass('glyphicon glyphicon-chevron-left').addClass('glyphicon glyphicon-chevron-down');\r\n");
      out.write("\t\t\t\t\tarr[i]=1;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(this).children().eq(0).children().last().removeClass('glyphicon glyphicon-chevron-down').addClass('glyphicon glyphicon-chevron-left');\r\n");
      out.write("\t\t\t\t\tarr[i]=0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
