/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2018-06-04 08:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.weixin.teacher;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class findTermSign_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>签到记录</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/mui.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/mui.picker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/mui.poppicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/wx.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"mui-bar mui-bar-nav\">\r\n");
      out.write("\t\t<a class=\"fa fa-chevron-left user_icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/weixin/teacher/sign.jsp\" style=\"font-size: 0.4rem!important;\"></a>\r\n");
      out.write("\t\t<a class=\"mui-icon mui-icon-info-filled mui-pull-right\"></a>\r\n");
      out.write("\t\t<h1 class=\"mui-title\">学期签到记录</h1>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div class=\"mui-content\">\r\n");
      out.write("\t\t<div class=\"mui-content-padded\">\r\n");
      out.write("\t\t\t\t<button id='showYearPicker' class=\"mui-btn mui-btn-block\" type='button'>请选择学期</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/flexible.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/mui.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/mui.picker.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/mui.poppicker.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t(function($, doc) {\r\n");
      out.write("\t\t$.init();\r\n");
      out.write("\t\t$.ready(function() {\r\n");
      out.write("\t\t\t//普通示例\r\n");
      out.write("\t\t\tvar yearPicker = new $.PopPicker();\r\n");
      out.write("\t\t\tvar cityData=([{\r\n");
      out.write("\t\t\t\tvalue: 2017,\r\n");
      out.write("\t\t\t\ttext: '2017',\r\n");
      out.write("\t\t\t\t children: [{\r\n");
      out.write("\t\t\t\t\t //2017-02-01 === 2017-08-01\r\n");
      out.write("\t                value:'1485878400,1501516800',\r\n");
      out.write("\t                text: \"上半学期\"\r\n");
      out.write("\t\t        },{\r\n");
      out.write("\t\t        \t//2017-09-01 === 2018-01-30\r\n");
      out.write("\t\t        \t value:'1504195200,1517241600',\r\n");
      out.write("\t\t             text: \"下半学期\"\r\n");
      out.write("\t\t        }]\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tvalue: 2018,\r\n");
      out.write("\t\t\t\ttext: '2018',\r\n");
      out.write("\t\t\t\t children: [{\r\n");
      out.write("\t\t                value:'1517414400,1533052800',\r\n");
      out.write("\t\t                text: \"上半学期\"\r\n");
      out.write("\t\t\t        },{\r\n");
      out.write("\t\t\t        \t value:'1535731200,1548777600',\r\n");
      out.write("\t\t\t             text: \"下半学期\"\r\n");
      out.write("\t\t\t        }]\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tvalue: 2019,\r\n");
      out.write("\t\t\t\ttext: '2019',\r\n");
      out.write("\t\t\t\t children: [{\r\n");
      out.write("\t\t                value:'1548950400,1564588800',\r\n");
      out.write("\t\t                text: \"上半学期\"\r\n");
      out.write("\t\t\t        },{\r\n");
      out.write("\t\t\t        \t value:'1567267200,1580313600',\r\n");
      out.write("\t\t\t             text: \"下半学期\"\r\n");
      out.write("\t\t\t        }]\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tvalue: 2020,\r\n");
      out.write("\t\t\t\ttext: '2020'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tvalue: 2021,\r\n");
      out.write("\t\t\t\ttext: '2021'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tvalue: 2022,\r\n");
      out.write("\t\t\t\ttext: '2022'\r\n");
      out.write("\t\t\t}]);\r\n");
      out.write("\t\t\t//级联示例\r\n");
      out.write("\t\t\tvar yearPicker = new $.PopPicker({\r\n");
      out.write("\t\t\t\tlayer: 2\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tyearPicker.setData(cityData);\r\n");
      out.write("\t\t\tvar showYearPickerButton = doc.getElementById('showYearPicker');\r\n");
      out.write("\t\t\tshowYearPickerButton.addEventListener('tap', function(event) {\r\n");
      out.write("\t\t\t\tyearPicker.show(function(items) {\r\n");
      out.write("\t\t\t\t\tvar signtime=items[1].value;\r\n");
      out.write("\t\t\t\t\tshowYearPickerButton.innerText = \"你选择的学期是:\" + items[0].text + \" \" + items[1].text;\r\n");
      out.write("\t\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sign/findTermSign?signtime=\"+signtime;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}, false);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})(mui, document);\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
