/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2018-06-04 13:02:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.weixin.teacher;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class random_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>签到记录</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("<!--æ åmui.css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/mui.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/personal.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t*{padding: padding:0;margin: 0;}\r\n");
      out.write("\t.title{\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t   height: 278px;\r\n");
      out.write("\t   margin: 0 auto;\r\n");
      out.write("\t   padding-top: 130px;\r\n");
      out.write("\t   text-align: center;\r\n");
      out.write("\t   font-size: 24px;\r\n");
      out.write("\t   font-weight: bold;\r\n");
      out.write("\t   color: #f00;\r\n");
      out.write("\t   background: url(../../images/random.jpg)no-repeat;\r\n");
      out.write("\t   background-size: 100%;\r\n");
      out.write("\t           \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.btns{\r\n");
      out.write("\t\twidth: 190px;\r\n");
      out.write("        height: 30px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.btns span{\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("       width: 80px;\r\n");
      out.write("       line-height: 27px;\r\n");
      out.write("       background: #036;\r\n");
      out.write("       border: 1px solid #eee;\r\n");
      out.write("       border-radius: 7px;\r\n");
      out.write("       margin-right: 10px;\r\n");
      out.write("       color: #fff;\r\n");
      out.write("       text-align: center;\r\n");
      out.write("       font-size: 14px;\r\n");
      out.write("       cursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"mui-bar mui-bar-nav\">\r\n");
      out.write("\t\t<a class=\"fa fa-chevron-left info_icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/weixin/teacher/sign.jsp\"></a>\r\n");
      out.write("\t\t<a class=\"mui-icon mui-icon-info-filled mui-pull-right\"></a>\r\n");
      out.write("\t\t<h1 class=\"mui-title\">随机抽查</h1>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div class=\"mui-content\">\r\n");
      out.write("\t\t<div id=\"title\" class=\"title\">开始抽查啦！</div>\r\n");
      out.write("\t\t<div class=\"btns\">\r\n");
      out.write("\t\t\t<span id=\"play\">开始</span>\r\n");
      out.write("\t\t\t<span id=\"stop\">停止</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t$('#play').click(function(){\r\n");
      out.write("\t\t\t$.get('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sign/random',function(data){\r\n");
      out.write("\t\t\t\tvar json=[];\r\n");
      out.write("\t\t\t\t$.each(data,function(indexs,items){\r\n");
      out.write("\t\t\t\t\tvar html='<input type=\"hidden\" name=\"id\" value=\"'+items.id+'\"/><span>'+items.name+'</span><br/><span>'+items.sno+'</span>';\r\n");
      out.write("\t\t\t\t\tjson.push(html);\r\n");
      out.write("\t\t\t\t\t$('#stop').click(function(){\r\n");
      out.write("\t\t\t\t\t\tstopFun();\r\n");
      out.write("\t\t\t\t\t\tvar id=$('input[name=\"id\"]').val();\r\n");
      out.write("\t\t\t\t\t\t//查询签到记录\r\n");
      out.write("\t\t\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sign/findSignByRandom?id=\"+id;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tplayFun(json);\r\n");
      out.write("\t\t\t},\"json\");\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t \ttimer=null,\r\n");
      out.write("\t    flag=0;\r\n");
      out.write("\t\tfunction playFun(data){\r\n");
      out.write("\t\t\tvar title=document.getElementById('title');\r\n");
      out.write("\t\t\tvar play=document.getElementById('play');\r\n");
      out.write("\t\t\tclearInterval(timer); \r\n");
      out.write("\t\t\ttimer=setInterval(function(){\r\n");
      out.write("\t\t\t   var random=Math.floor(Math.random()*data.length);//floor（）向下取整，random（）0-1随机数\r\n");
      out.write("\t\t\t   title.innerHTML=data[random];\r\n");
      out.write("\t\t\t},50);\r\n");
      out.write("\t\t    play.style.background='#999';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction stopFun(){\r\n");
      out.write("\t\t\tclearInterval(timer);\r\n");
      out.write("\t\t\tvar play=document.getElementById('play');\r\n");
      out.write("\t\t\tplay.style.background='#036';\r\n");
      out.write("\t\t} \r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
