/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2018-05-12 08:45:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.weixin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tch_005fpersonal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>扫码签到</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("<!--标准mui.css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/mui.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/wx.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/teacher.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"mui-bar mui-bar-nav\">\r\n");
      out.write("\t\t<a class=\"fa fa-user user_icon\"></a>\r\n");
      out.write("\t\t<a class=\"mui-icon mui-icon-info-filled mui-pull-right\"></a>\r\n");
      out.write("\t\t<h1 class=\"mui-title\">个人中心</h1>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div class=\"mui-content\">\r\n");
      out.write("\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t<img src=\"../images/st1.jpg\" class=\"bg-img\"/>\r\n");
      out.write("\t\t\t<div class=\"head-info\">\r\n");
      out.write("\t\t\t\t<div><img src=\"../images/ggn.PNG\" class=\"head-img\" width=\"60\" height=\"60\" /></div>\r\n");
      out.write("\t\t\t\t<div>静</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span class=\"fa fa-address-card-o\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"font-12-size\" style=\"color: #fc681f;\">教师</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mui-card\">\r\n");
      out.write("\t        <ul class=\"mui-table-view\">\r\n");
      out.write("\t            <li class=\"mui-table-view-cell\">\r\n");
      out.write("\t                <a class=\"mui-navigate-right\">\r\n");
      out.write("\t                \t<span class=\"fa fa-calendar-plus-o\" style=\"color:#40c1df\"></span>\r\n");
      out.write("\t                    <span class=\"mui-badge mui-badge-danger\">15</span>\r\n");
      out.write("\t                   \t<span style=\"padding-left: .5rem;\">教学安排</span>\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li class=\"mui-table-view-cell\">\r\n");
      out.write("\t                <a class=\"mui-navigate-right\">\r\n");
      out.write("\t                    <span class=\"mui-badge mui-badge-purple\">5</span>\r\n");
      out.write("\t                    Item 2\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li class=\"mui-table-view-cell\">\r\n");
      out.write("\t                <a class=\"mui-navigate-right\">\r\n");
      out.write("\t                    <span class=\"mui-badge mui-badge-warning\">5</span>\r\n");
      out.write("\t                    Item 3\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav class=\"mui-bar mui-bar-tab\">\r\n");
      out.write("\t\t<a class=\"mui-tab-item mui-active\" href=\"#tabbar\">\r\n");
      out.write("\t\t\t<span class=\"mui-icon mui-icon-home\"></span>\r\n");
      out.write("\t\t\t<span class=\"mui-tab-label\">首页</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<a class=\"mui-tab-item\" href=\"#tabbar-with-chat\">\r\n");
      out.write("\t\t\t<span class=\"mui-icon mui-icon-email\"><span class=\"mui-badge\">9</span></span>\r\n");
      out.write("\t\t\t<span class=\"mui-tab-label\">消息</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<a class=\"mui-tab-item\" href=\"#tabbar-with-contact\">\r\n");
      out.write("\t\t\t<span class=\"mui-icon mui-icon-contact\"></span>\r\n");
      out.write("\t\t\t<span class=\"mui-tab-label\">通讯录</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<a class=\"mui-tab-item\" href=\"#tabbar-with-map\">\r\n");
      out.write("\t\t\t<span class=\"mui-icon mui-icon-gear\"></span>\r\n");
      out.write("\t\t\t<span class=\"mui-tab-label\">设置</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
